class LoadSpinner extends HTMLElement {
  connectedCallback() {
    this.render();
  }

  render() {
    this.innerHTML = `
    <div class="loadingio-spinner-rolling-du3xyk89m7"><div class="ldio-6j7bcluzhol">
    <div></div>
    </div></div>
    <style type="text/css">
    @keyframes ldio-6j7bcluzhol {
    0% { transform: translate(-50%,-50%) rotate(0deg); }
    100% { transform: translate(-50%,-50%) rotate(360deg); }
    }
    .ldio-6j7bcluzhol div {
    position: absolute;
    width: 53px;
    height: 53px;
    border: 17px solid #faaa00;
    border-top-color: transparent;
    border-radius: 50%;
    }
    .ldio-6j7bcluzhol div {
    animation: ldio-6j7bcluzhol 1s linear infinite;
    top: 50px;
    left: 50px
    }
    .loadingio-spinner-rolling-du3xyk89m7 {
    width: 84px;
    height: 84px;
    display: inline-block;
    overflow: hidden;
    background: none;
    }
    .ldio-6j7bcluzhol {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.84);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
    }
    .ldio-6j7bcluzhol div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>
    `;
  }
}

customElements.define('load-spinner', LoadSpinner);
